sudo: required
dist: trusty

language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.2

cache:
  apt: true
  directories:
    - $HOME/.stack/
    - .stack-work/

before_install: mkdir -p $HOME/.local/bin
install:
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - pip install --user --upgrade awscli

before_script: rm -rf .build
script: ./Shakefile.hs docker:travis

env:
  global:
    - PATH=$HOME/.local/bin:/opt/ghc/8.2.2/bin:$PATH
    - AWS_DEFAULT_REGION=us-west-2
    - secure: "SFTOtZpUeC5bYQVfZeJJ2xpJAf/HVvid2KfW6KVERDzmX1OgRF5nI61kKzP40xLXPeEdhqAtGK31KM2zyVBzB+pJXougGwxTmsTaJT5UWbl4fDm2DWEkITt+b2IKRng/dWje0MB9eGGNTb08Y5sIQZLgk9JvwuAR+9plM4Z0ZYVnv6yjpKh3kpCrOLBCExfApYa+eE1HZ1yM1lXRMBeHaVdF9c/yGoiKpcZcNzpfysjm2BjrAgJGFEfASRvlUo5HoLkcUkawcBohJZq3C6PM8DLWXtpU7Ey6eR0JG1LhA30WLOQywNVe0umFlKQjM7HK7Wsy+Q3ywYGIvAxnNXasFsUIDhFoSFr6Eu4q1GqHfZUEW7Z5IrGiEO+ql4r5vVYiYk5F+dvYxksPKDb+reE9vAwxTUMOmm2wgLbMUOcXr/Oj/Eg3qTYk5Ukax1GjX0oalblmAS2QIOijftJe5kOJ1gJ84QBQ23YKQhmXK1TccoMZDp9zAWRVaKfyl4J+vFeoqA9rFEfSfU4cVyczKt5UacTE1tggnvvGuug7Ft9sVnyqtEQBU4BW8TdJzBj9mQguUgE8V5ElSTVIHK2XtJ4Raiyz2QD/KiPHX5IOsc0v41ACThQ88+6K3OL7XytNmklIKp5/aKnMtjiucBCQwieZsIlUFozRQRBJmMglF7gcLgk="
    - secure: "qQ27Hs6gFe7xfC8bmMTkDS8rmTkxf7pPRuVGuo8uyHCFp0i5+Hi7to6ytXoux+G5htFHSkd3EYu3FJ/YBu4QYaPnm2IzdYkE3NXviXAFOQ68+ew7XLLJFAzQLE7tONPLpPTUUkUcfkYhlsEl5Ksxvhha6fb08ukiqh3ZcQxt5axQA+vMu8g7i2l7s0QQUIBliF/Dfy4bhuC5vHgk5SPNKFNF8P63l3wYjow1XvvB0mnIT2hoDXRqCSpBy1MvVyj4U/hIrbdyyCs2xhRgrbqLrHHUdRWG5mZxl0QX1Y/9QvtKz8FdEBsjTcW8lglrHt6iFvhFStl0lwPTF1oGf+czvci7O1sfGsHXj3W0oEEJ7u9UrvGDUwsXCkFM6QM10rzsYzsJ9YZime/i0CbbFWVaFHSYbjn8liiHHkGPE5U4IhZ24Bpe4l6m+9O38kRa8bK/HmbFPEAcd+fT2Jz8UPxbriPTOBVVeTMLNZr9XYEeZkGQ0cuUvFO6AFDE9dxoQHJ8xGMXDZy3kae+HlhwB7LaklpFXWJ+NgM2KYi3djf505eNMfRCARG89ZGBH0sUsPgqb0wg9ItaB8pqnUnqZXDBHu0JUYqeT/tbm16rPM19ax/wDPG1pnQj2zvv0HXh2S1kNt0hQqUBq6oGL524gWTmQUrFSoMo3TEPKkd1i2eMYck="
