name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: haskell/actions/setup@v1.2.1
      with:
        enable-stack: true
        ghc-version: '8.2'
        stack-version: 'latest'
    - name: Build
      run:  stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
